---

version: "2.4"
services:
  neofs_morph_chain:
    image: nspccdev/neo-go:${NEOGO_VERSION}
    container_name: morph_chain
    command: ["node", "--config-path", "/config", "--privnet", "--debug"]
    domainname: ${LOCAL_DOMAIN}
    hostname: morph-chain
    networks:
      chain_int:
      internet:
        ipv4_address: ${IPV4_PREFIX}.90
    stop_signal: SIGKILL
    env_file: [ ".int_test.env" ]
    volumes:
    - ./protocol.privnet.yml:/config/protocol.privnet.yml
    - ./node-wallet.json:/wallets/node-wallet.json
    - ./../../vendor/hosts:/etc/hosts
    - ./../../wallets/wallet.json:/wallets/wallet.json

networks:
  chain_int:
  internet:
    external: true
    name: basenet_internet
