---

version: "2.4"
services:
  nats:
    image: ${NATS_IMAGE}:${NATS_VERSION}
    domainname: ${LOCAL_DOMAIN}
    hostname: nats
    container_name: nats
    restart: "no"
    dns: 
      - ${IPV4_PREFIX}.101
    networks:
      nats_int:
      internet:
        ipv4_address: ${IPV4_PREFIX}.101
    volumes:
      - ./../../vendor/hosts:/etc/hosts
      - ./nats.conf:/etc/nats/neofs-nats-server.conf
      - ./server-cert.pem:/certs/server-cert.pem
      - ./server-key.pem:/certs/server-key.pem
      - ./ca-cert.pem:/certs/ca-cert.pem
    stop_signal: SIGKILL
    env_file: [ ".env", ".int_test.env" ]
    command: ["-c", "/etc/nats/neofs-nats-server.conf"]

networks:
  nats_int:
  internet:
    external: true
    name: basenet_internet
